name: App Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Gradle
        uses: gradle/wrapper-action@v1
        with:
          gradle-version: '7.0'

      - name: Build APK
        run: ./gradlew assembleRelease
