name: Android Build

on:
  push:
    branches:
      - master  # Pastikan branch yang benar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Menggunakan Temurin sebagai distribusi JDK

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.9'  # Menggunakan versi Gradle 8.9

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew  # Memberikan izin eksekusi pada gradlew

      - name: Build APK
        run: ./gradlew assembleRelease  # Jalankan gradlew untuk build APK
